// Server Component — no "use client"
import Link from "next/link";

type Locale = "en" | "ko";

const content = {
  en: {
    features: {
      heading: "Why DraftURL?",
      items: [
        {
          title: "3-Second Deploy",
          description:
            "Just paste and click. No signup, no config, no build step — get a shareable URL instantly.",
        },
        {
          title: "Live Preview",
          description:
            "See your HTML or Markdown rendered in real time before sharing.",
        },
        {
          title: "Clean Shareable URLs",
          description:
            "Get short, clean URLs like drafturl.com/xK9mP2nQ — easy to copy and share anywhere.",
        },
        {
          title: "AI-Ready",
          description:
            "Paste documents generated by ChatGPT, Claude, or any AI and share them in seconds.",
        },
      ],
    },
    steps: {
      heading: "How to share a document",
      items: [
        {
          title: "Paste or Drag & Drop",
          description:
            "Paste HTML or Markdown from ChatGPT, Claude, or any LLM into the editor — or drag & drop an .html/.md file.",
        },
        {
          title: "Check the Preview",
          description:
            "See the result in the live preview on the right. Edit on the spot if needed.",
        },
        {
          title: "Get a Share URL",
          description:
            "Click Share and get a unique URL instantly. Send it to anyone — no account needed.",
        },
      ],
    },
    faq: {
      heading: "Frequently Asked Questions",
      items: [
        {
          q: "What is DraftURL?",
          a: "DraftURL is a free tool that lets you share HTML and Markdown documents via a unique URL instantly. Paste your content, click Share, and get a link — no signup required.",
        },
        {
          q: "Do I need to sign up to use DraftURL?",
          a: "No signup is required. You can create and share documents as a guest. Guest documents automatically expire after 24 hours. Log in with Google or GitHub to keep documents permanently.",
        },
        {
          q: "What file formats does DraftURL support?",
          a: "DraftURL supports HTML (.html, .htm) and Markdown (.md, .markdown) documents up to 5MB in size.",
        },
        {
          q: "How long are shared documents kept?",
          a: "Guest documents expire after 24 hours. Documents created by logged-in users are stored permanently.",
        },
        {
          q: "Can I edit a document after sharing?",
          a: "Yes. Logged-in users can edit their documents at any time from the dashboard. Guest documents cannot be modified after sharing.",
        },
        {
          q: "Is DraftURL free?",
          a: "Yes, DraftURL is completely free to use. No credit card or signup required for basic usage.",
        },
      ],
    },
    footer: {
      terms: "Terms of Service",
      privacy: "Privacy Policy",
    },
  },
  ko: {
    features: {
      heading: "DraftURL이란?",
      items: [
        {
          title: "3초 배포",
          description:
            "붙여넣고 버튼 하나면 끝. 가입, 설정, 빌드 없이 즉시 공유 URL이 생성됩니다.",
        },
        {
          title: "실시간 미리보기",
          description:
            "HTML이나 Markdown이 렌더링된 결과를 공유 전에 실시간으로 확인할 수 있습니다.",
        },
        {
          title: "깔끔한 공유 URL",
          description:
            "drafturl.com/xK9mP2nQ 형태의 간결한 URL로 누구에게나 쉽게 공유하세요.",
        },
        {
          title: "AI 문서에 최적화",
          description:
            "ChatGPT, Claude 등 AI가 생성한 HTML/Markdown 문서를 즉시 공유할 수 있습니다.",
        },
      ],
    },
    steps: {
      heading: "이렇게 사용하세요",
      items: [
        {
          title: "붙여넣기 또는 드래그앤드롭",
          description:
            "ChatGPT, Claude 등 LLM이 생성한 HTML이나 Markdown을 붙여넣거나, .html/.md 파일을 드래그앤드롭하세요.",
        },
        {
          title: "미리보기 확인",
          description:
            "오른쪽 미리보기에서 결과를 실시간으로 확인하고, 필요하면 바로 수정하세요.",
        },
        {
          title: "공유 URL 발급",
          description:
            "공유하기 버튼 한 번이면 고유 URL이 즉시 생성됩니다. 누구에게나 보낼 수 있습니다.",
        },
      ],
    },
    faq: {
      heading: "자주 묻는 질문",
      items: [
        {
          q: "DraftURL이 무엇인가요?",
          a: "DraftURL은 HTML이나 Markdown 문서를 고유 URL로 즉시 공유할 수 있는 무료 서비스입니다. 내용을 붙여넣고 공유 버튼을 클릭하면 링크가 바로 생성됩니다. 회원가입이 필요 없습니다.",
        },
        {
          q: "회원가입 없이 사용할 수 있나요?",
          a: "네, 가입 없이도 바로 사용할 수 있습니다. 비로그인 문서는 24시간 후 자동 만료됩니다. Google 또는 GitHub으로 로그인하면 문서를 영구적으로 보관할 수 있습니다.",
        },
        {
          q: "어떤 파일 형식을 지원하나요?",
          a: "HTML(.html, .htm)과 Markdown(.md, .markdown) 파일을 지원합니다. 최대 파일 크기는 5MB입니다.",
        },
        {
          q: "공유한 문서는 얼마나 보관되나요?",
          a: "비로그인으로 만든 문서는 24시간 후 자동 만료됩니다. 로그인 사용자의 문서는 영구적으로 보관됩니다.",
        },
        {
          q: "공유 후 문서를 수정할 수 있나요?",
          a: "로그인 사용자는 대시보드에서 자신의 문서를 언제든지 수정할 수 있습니다. 비로그인 문서는 공유 후 수정이 불가능합니다.",
        },
        {
          q: "DraftURL은 무료인가요?",
          a: "네, 완전 무료로 사용할 수 있습니다. 기본 기능은 신용카드나 회원가입 없이 이용 가능합니다.",
        },
      ],
    },
    footer: {
      terms: "이용약관",
      privacy: "개인정보 처리방침",
    },
  },
};

export default function HomeStaticSections({ locale }: { locale: Locale }) {
  const t = content[locale];

  return (
    <>
      {/* Feature Cards */}
      <section className="max-w-[1280px] mx-auto w-full px-6 pb-4">
        <h2 className="text-xl font-bold text-text-primary text-center mb-8">
          {t.features.heading}
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {t.features.items.map((feature) => (
            <div
              key={feature.title}
              className="bg-bg-secondary border border-border-dark rounded-xl p-6 hover:border-border-dark-hover transition-colors"
            >
              <h3 className="text-[15px] font-semibold mb-1.5 text-text-primary">
                {feature.title}
              </h3>
              <p className="text-[13px] text-text-secondary leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* How-to-Use Steps */}
      <section className="max-w-[1280px] mx-auto w-full px-6 py-8">
        <h2 className="text-xl font-bold text-text-primary text-center mb-8">
          {t.steps.heading}
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {t.steps.items.map((step, index) => (
            <div
              key={step.title}
              className="relative bg-bg-secondary border border-border-dark rounded-xl p-6"
            >
              <div className="w-8 h-8 rounded-full bg-accent text-white flex items-center justify-center text-sm font-bold mb-3">
                {index + 1}
              </div>
              <h3 className="text-[15px] font-semibold mb-1.5 text-text-primary">
                {step.title}
              </h3>
              <p className="text-[13px] text-text-secondary leading-relaxed">
                {step.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* FAQ Section */}
      <section className="max-w-[1280px] mx-auto w-full px-6 py-8 mb-4">
        <h2 className="text-xl font-bold text-text-primary text-center mb-8">
          {t.faq.heading}
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-w-4xl mx-auto">
          {t.faq.items.map((item) => (
            <div
              key={item.q}
              className="bg-bg-secondary border border-border-dark rounded-xl p-6"
            >
              <h3 className="text-[14px] font-semibold text-text-primary mb-2">
                {item.q}
              </h3>
              <p className="text-[13px] text-text-secondary leading-relaxed">
                {item.a}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border-dark mt-auto">
        <div className="max-w-screen-xl mx-auto px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-text-muted/60">
          <span>&copy; 2026 DraftURL</span>
          <div className="flex items-center gap-4">
            <Link
              href="/terms"
              className="hover:text-text-muted transition-colors"
            >
              {t.footer.terms}
            </Link>
            <Link
              href="/privacy"
              className="hover:text-text-muted transition-colors"
            >
              {t.footer.privacy}
            </Link>
          </div>
        </div>
      </footer>
    </>
  );
}
