import type { Metadata } from "next";
import { headers } from "next/headers";
import Link from "next/link";
import type { Locale } from "@/dictionaries/types";

export const metadata: Metadata = {
  title: "Guide — DraftURL",
  description: "DraftURL usage guides and tutorials",
};

/* 아이콘 */
const guideIcons = [
  /* Plug — MCP 연결 */
  <svg key="plug" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22v-5" /><path d="M9 8V2" /><path d="M15 8V2" /><path d="M18 8v5a6 6 0 0 1-12 0V8z" /></svg>,
  /* BookOpen — 시작하기 */
  <svg key="book" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>,
];

const content = {
  en: {
    heading: "Guide",
    subtitle: "Learn how to use DraftURL effectively.",
    guides: [
      {
        href: "/guide/mcp",
        title: "MCP Connection",
        description: "Connect Claude Desktop, Claude Code, or Cursor to DraftURL via MCP.",
      },
    ],
    gettingStarted: {
      heading: "Getting Started",
      steps: [
        {
          title: "Paste or Drag & Drop",
          description: "Paste HTML or Markdown from ChatGPT, Claude, or any LLM — or drag & drop an .html/.md file.",
        },
        {
          title: "Preview",
          description: "Check the rendered result before sharing. Edit if needed.",
        },
        {
          title: "Get a Share URL",
          description: "Click Share and get a unique URL instantly. Send it to anyone — no account needed.",
        },
      ],
    },
    features: {
      heading: "Features",
      items: [
        { title: "3-Second Deploy", description: "Just paste and click. No signup, no config — get a shareable URL instantly." },
        { title: "Preview Before Sharing", description: "Preview your HTML or Markdown document before sharing to make sure it looks right." },
        { title: "Clean Shareable URLs", description: "Get short, clean URLs like drafturl.com/xK9mP2nQ." },
        { title: "AI-Ready", description: "Paste documents generated by ChatGPT, Claude, or any AI and share them in seconds." },
      ],
    },
    faq: {
      heading: "FAQ",
      items: [
        { q: "What is DraftURL?", a: "DraftURL is a free tool that lets you share HTML and Markdown documents via a unique URL instantly. No signup required." },
        { q: "Do I need to sign up?", a: "No. Guest documents expire after 24 hours. Log in to keep documents permanently." },
        { q: "What formats are supported?", a: "HTML (.html, .htm) and Markdown (.md, .markdown) up to 5MB." },
        { q: "How long are documents kept?", a: "Guest: 24 hours. Logged-in users: permanently." },
        { q: "Can I edit after sharing?", a: "Logged-in users can change the document title from the dashboard. Content editing is available via MCP tools (update_document). Guest documents cannot be modified." },
      ],
    },
  },
  ko: {
    heading: "가이드",
    subtitle: "DraftURL 사용 방법을 안내합니다.",
    guides: [
      {
        href: "/guide/mcp",
        title: "MCP 연결",
        description: "Claude Desktop, Claude Code, Cursor에서 MCP로 DraftURL에 연결하는 방법.",
      },
    ],
    gettingStarted: {
      heading: "시작하기",
      steps: [
        {
          title: "붙여넣기 또는 드래그앤드롭",
          description: "ChatGPT, Claude 등 LLM이 생성한 HTML이나 Markdown을 붙여넣거나, .html/.md 파일을 드래그앤드롭하세요.",
        },
        {
          title: "미리보기 확인",
          description: "렌더링된 결과를 공유 전에 확인하고, 필요하면 수정하세요.",
        },
        {
          title: "공유 URL 발급",
          description: "공유하기 버튼 한 번이면 고유 URL이 즉시 생성됩니다.",
        },
      ],
    },
    features: {
      heading: "주요 기능",
      items: [
        { title: "3초 배포", description: "붙여넣고 버튼 하나면 끝. 가입, 설정, 빌드 없이 즉시 공유 URL이 생성됩니다." },
        { title: "공유 전 미리보기", description: "문서를 공유하기 전에 렌더링된 결과를 미리 확인할 수 있습니다." },
        { title: "깔끔한 공유 URL", description: "drafturl.com/xK9mP2nQ 형태의 간결한 URL로 누구에게나 쉽게 공유하세요." },
        { title: "AI 문서에 최적화", description: "ChatGPT, Claude 등 AI가 생성한 HTML/Markdown 문서를 즉시 공유할 수 있습니다." },
      ],
    },
    faq: {
      heading: "자주 묻는 질문",
      items: [
        { q: "DraftURL이 무엇인가요?", a: "HTML이나 Markdown 문서를 고유 URL로 즉시 공유할 수 있는 무료 서비스입니다. 회원가입이 필요 없습니다." },
        { q: "회원가입 없이 사용할 수 있나요?", a: "네. 비로그인 문서는 24시간 후 만료됩니다. 로그인하면 영구 보관됩니다." },
        { q: "어떤 파일 형식을 지원하나요?", a: "HTML(.html, .htm)과 Markdown(.md, .markdown)을 지원합니다. 최대 5MB." },
        { q: "공유한 문서는 얼마나 보관되나요?", a: "비로그인: 24시간. 로그인 사용자: 영구 보관." },
        { q: "공유 후 수정할 수 있나요?", a: "로그인 사용자는 대시보드에서 제목을 변경할 수 있습니다. 문서 내용 수정은 MCP 도구(update_document)로 가능합니다. 비로그인 문서는 수정할 수 없습니다." },
      ],
    },
  },
};

/* Feature 아이콘 */
const featureIcons = [
  <svg key="zap" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" /></svg>,
  <svg key="eye" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" /><circle cx="12" cy="12" r="3" /></svg>,
  <svg key="link" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" /><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" /></svg>,
  <svg key="sparkles" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z" /><path d="M5 3v4" /><path d="M19 17v4" /><path d="M3 5h4" /><path d="M17 19h4" /></svg>,
];

export default async function GuidePage() {
  const headersList = await headers();
  const locale = (headersList.get("x-locale") ?? "ko") as Locale;
  const t = content[locale];

  return (
    <main>
      <div className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="mb-2 text-2xl font-bold text-text-primary">
          {t.heading}
        </h1>
        <p className="mb-10 text-sm text-text-secondary">{t.subtitle}</p>

        {/* Guide List — 실용 가이드 최상단 */}
        <section className="mb-10">
          <div className="grid gap-4">
            {t.guides.map((guide, index) => (
              <Link
                key={guide.href}
                href={guide.href}
                className="flex items-start gap-4 rounded-xl border border-border-dark bg-bg-secondary p-5 transition-colors hover:border-accent/30"
              >
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-accent/15 text-accent">
                  {guideIcons[index]}
                </div>
                <div>
                  <h2 className="mb-1 text-[15px] font-semibold text-text-primary">
                    {guide.title}
                  </h2>
                  <p className="text-[13px] leading-relaxed text-text-secondary">
                    {guide.description}
                  </p>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* Getting Started — 3 Steps */}
        <section className="mb-10">
          <h2 className="mb-6 text-lg font-bold text-text-primary">
            {t.gettingStarted.heading}
          </h2>
          <div className="flex flex-col gap-3">
            {t.gettingStarted.steps.map((step, index) => (
              <div
                key={step.title}
                className="flex items-start gap-3.5 rounded-xl border border-border-dark bg-bg-secondary p-5"
              >
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-accent text-sm font-bold text-white">
                  {index + 1}
                </div>
                <div>
                  <h3 className="mb-1 text-[14px] font-semibold text-text-primary">
                    {step.title}
                  </h3>
                  <p className="text-[13px] leading-relaxed text-text-secondary">
                    {step.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Features */}
        <section className="mb-10">
          <h2 className="mb-6 text-lg font-bold text-text-primary">
            {t.features.heading}
          </h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {t.features.items.map((feature, index) => (
              <div
                key={feature.title}
                className="rounded-xl border border-border-dark bg-bg-secondary p-5"
              >
                <div className="mb-2.5 flex h-8 w-8 items-center justify-center rounded-lg bg-accent/15 text-accent">
                  {featureIcons[index]}
                </div>
                <h3 className="mb-1 text-[14px] font-semibold text-text-primary">
                  {feature.title}
                </h3>
                <p className="text-[13px] leading-relaxed text-text-secondary">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </section>

        {/* FAQ */}
        <section>
          <h2 className="mb-6 text-lg font-bold text-text-primary">
            {t.faq.heading}
          </h2>
          <div className="flex flex-col gap-3">
            {t.faq.items.map((item) => (
              <div
                key={item.q}
                className="rounded-xl border border-border-dark bg-bg-secondary p-5"
              >
                <h3 className="mb-1.5 text-[14px] font-semibold text-text-primary">
                  {item.q}
                </h3>
                <p className="text-[13px] leading-relaxed text-text-secondary">
                  {item.a}
                </p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </main>
  );
}
